workflows:
  flutter-build:
    name: Flutter Android and iOS Build

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Flutter analyze
        script: |
          flutter analyze || true

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa