workflows:
  flutter-build:
    name: Flutter iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa